openapi: "3.0.0"
info:
  title: BookStore
  description: APIs for book store
  version: 1.0.0
  contact:  
    email: anjaneya.singh94@gmail.com
    url: "https://github.com/asp89"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: Local Host
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /status:
    get:
      tags:
        - Status
      summary: returns server message
      responses:
        200:
          description: All good status
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad Request
        500:
          desciption: Internal Server Error